# Configuration file for `isort`.
#
# Invocation:
#
#   cd drake
#   isort .
#
# For more information:
# - https://timothycrosley.github.io/isort/
# - (Permalink) https://github.com/timothycrosley/isort/blob/5.6.4/README.md

[tool.isort]
# Based on `profile = black`, but with customizations.
force_grid_wrap = false
force_sort_within_sections = true
honor_noqa = true
include_trailing_comma = true
multi_line_output = 3  # Vertical Hanging Indent
use_parentheses = true
ignore_comments = true

skip = [
    ".git",
    "build",
    "all.py",
]
skip_glob = [
    "bazel-*/",
]

# [ Sections ]
# See: https://github.com/timothycrosley/isort#custom-sections-and-ordering
# This determines the ordering of imports.
sections = [
    # {builtin}
    "FUTURE",
    # {builtin}
    "STDLIB",
    # known_third_party
    "THIRDPARTY",
    # known_first_party
    "FIRSTPARTY",
    # {builtin}
    "LOCALFOLDER",
]
default_section = "THIRDPARTY"
known_third_party = []
known_first_party = [
    "drake",
    "pydrake",
]
